# Generated by Django 3.2.5 on 2021-07-30 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fan', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='fan.creator'),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
