# Generated by Django 3.2.5 on 2021-07-30 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fan', '0005_prize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fan.event')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fan.fan')),
            ],
        ),
    ]
