# Generated by Django 3.2.5 on 2021-07-31 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fan', '0006_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='prize',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fan.prize'),
        ),
        migrations.AddField(
            model_name='entry',
            name='won',
            field=models.BooleanField(null=True),
        ),
    ]
