# Generated by Django 3.2.5 on 2021-07-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan', '0008_auto_20210731_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile/creator/'),
        ),
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile/event/'),
        ),
        migrations.AddField(
            model_name='fan',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile/fan'),
        ),
        migrations.AddField(
            model_name='prize',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile/prize'),
        ),
    ]
